FROM python:3.10

WORKDIR /app
COPY frontend/ /app

RUN pip install streamlit requests

CMD ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]


#FROM python:3.10

#WORKDIR /app

#COPY . /app

#RUN pip install --upgrade pip && pip install streamlit requests

#CMD ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
